version: "3.8"
services:
  gateway:
    image: gateway
    container_name: cogito_gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 7333:7333
    environment:
      - VIRTUAL_HOST=back.cogitodev.org
      - LETSENCRYPT_HOST=back.cogitodev.org
      - VIRTUAL_PORT=7333
      - PORT=7333

      - APP_URL=http://cogito_app:8000
    networks:
      - reverse-proxy
      - back

  controllers:
    image: controllers
    container_name: cogito_controllers
    build:
      context: ./controllers
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    networks:
      - back

  app:
    image: app
    container_name: cogito_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - REPOSITORY_URL=http://cogito_repositories:8001
      - MIDDLEWARE_URL=http://cogito_middleware:8002
    networks:
      - back

  telegram:
    image: telegram
    container_name: cogito_telegram
    build:
      context: ./client/telegram
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - reverse-proxy

  middleware:
    image: middleware
    container_name: cogito_middleware
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    networks:
      - back

  db:
    image: db
    container_name: cogito_db
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/initpg.sh:/docker-entrypoint-initdb.d/initpg.sh
    networks:
      - back

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

volumes:
  db:
