from pydantic import BaseModel


class UserGoalBase(BaseModel): ...


class UserGoalCreateDTO(UserGoalBase): ...


class UserGoalUpdateDTO(UserGoalBase): ...


class UserGoalResponseDTO(UserGoalBase): ...
